/**
 * The site's security headers, written once and served from two places:
 * public/_headers dresses prerendered pages Cloudflare serves without waking
 * the Worker, src/middleware.ts dresses everything else. Edit this file —
 * scripts/generate-headers.ts writes public/_headers out of it.
 *
 * Plain TypeScript, no Astro-isms: Vite, bare Node and astro.config.ts all
 * load it, and they do not understand the same things.
 */

export interface HeaderContext {
  /** In dev the cursor Worker is on its own port; in production `'self'` covers it. */
  dev?: boolean;
}

/** Both schemes: the socket, and the presence count beside it. */
const DEV_MULTIPLAYER = "ws://localhost:8788 http://localhost:8788";

export function securityHeaders({ dev = false }: HeaderContext = {}) {
  return {
    "X-Content-Type-Options": "nosniff",
    "X-Frame-Options": "DENY",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "Permissions-Policy": "camera=(), microphone=(), geolocation=(), payment=()",
    "Strict-Transport-Security": "max-age=63072000; includeSubDomains",
    "Content-Security-Policy": contentSecurityPolicy(dev),
  } satisfies Record<string, string>;
}

/**
 * Everything the policy says that is not about scripts or styles. Shared
 * verbatim with the `<meta>` CSP Astro emits, since a browser enforces both
 * and a directive in only one has two answers.
 */
function baseDirectives(dev = false): string[] {
  return [
    "default-src 'self'",
    "base-uri 'self'",
    "form-action 'self'",
    "object-src 'none'",
    "font-src 'self'",
    // The cursor socket. Same origin, but `'self'` covering ws/wss is a CSP3
    // clarification some browsers were late to, so spell out the scheme.
    `connect-src 'self' wss://rcn.sh${dev ? ` ${DEV_MULTIPLAYER}` : ""}`,
    // Spotify spreads art across several scdn.co subdomains, hence wildcards.
    "img-src 'self' data: https://*.scdn.co https://*.spotifycdn.com https://avatars.githubusercontent.com https://upload.rcn.sh",
    "upgrade-insecure-requests",
  ];
}

/**
 * The policy. `script-src` and `style-src` carry 'unsafe-inline' because this
 * header is written ahead of time and cannot name Astro's inline scripts.
 *
 * Hashing them is `security.csp`, which is off: it publishes the hashes in a
 * <meta> element, and <ClientRouter /> swaps document contents rather than
 * reparsing, so the entry page's hashes block every page reached from the nav.
 * See astro.config.ts. A known gap; nothing here renders raw HTML today.
 */
function contentSecurityPolicy(dev: boolean): string {
  return [
    ...baseDirectives(dev),
    "frame-ancestors 'none'",
    // Cloudflare injects the Web Analytics beacon at the edge. The host and not
    // the file, because the injected URL carries a version after it, and a CSP
    // path without a trailing slash has to match exactly. It reports back to
    // /cdn-cgi/rum here, which connect-src 'self' already covers.
    "script-src 'self' 'unsafe-inline' https://static.cloudflareinsights.com",
    "style-src 'self' 'unsafe-inline'",
  ].join("; ");
}

/** The contents of public/_headers. Always the production set. */
export function headersFile(): string {
  const rules = Object.entries(securityHeaders())
    .map(([name, value]) => `  ${name}: ${value}`)
    .join("\n");

  return `# Generated by scripts/generate-headers.ts — edit shared/security.ts.
#
# Statically served responses only; src/middleware.ts covers everything the
# Worker renders. The Cloudflare adapter appends its own /_astro/* rule here
# at build time.

/*
${rules}
`;
}
