import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { headersFile, securityHeaders, SCRIPT_SOURCES } from "./security.ts";

// public/_headers and src/middleware.ts must not drift apart.
describe("security headers", () => {
  test("the generated file carries every header the Worker sets", () => {
    const file = headersFile();

    for (const [name, value] of Object.entries(securityHeaders())) {
      assert.ok(
        file.includes(`  ${name}: ${value}`),
        `public/_headers is missing ${name}`,
      );
    }
  });

  test("the file is shaped the way Cloudflare parses it", () => {
    const lines = headersFile().split("\n");
    const rule = lines.indexOf("/*");

    assert.ok(rule !== -1, "no path pattern");
    // Everything after the pattern is an indented header, or the trailing gap.
    for (const line of lines.slice(rule + 1)) {
      if (line === "") continue;
      assert.match(line, /^ {2}[\w-]+: .+$/, `not a header line: ${line}`);
    }
  });

  test("localhost is a development-only exception", () => {
    assert.ok(!securityHeaders()["Content-Security-Policy"].includes("localhost"));
    assert.ok(
      securityHeaders({ dev: true })["Content-Security-Policy"].includes(
        "ws://localhost:8788",
      ),
    );
  });

  // Same Worker, same port: admitting one but not the other half-works.
  test("development admits both halves of the cursor Worker", () => {
    const policy = securityHeaders({ dev: true })["Content-Security-Policy"];

    assert.ok(policy.includes("ws://localhost:8788"));
    assert.ok(policy.includes("http://localhost:8788"));
  });

  // Asserts on SCRIPT_SOURCES, not on the header: the header was never the
  // broken half. A host in only the header is in neither binding policy.
  test("the Web Analytics beacon is admitted by host", () => {
    assert.ok(
      SCRIPT_SOURCES.includes("https://static.cloudflareinsights.com"),
      "the beacon host must be in SCRIPT_SOURCES, or Astro's <meta> blocks it",
    );
    assert.match(
      securityHeaders()["Content-Security-Policy"],
      /script-src[^;]* https:\/\/static\.cloudflareinsights\.com(?=[ ;]|$)/,
    );
  });

  // Astro's `resources` replaces its default rather than extending it.
  test("same-origin scripts survive the meta policy", () => {
    assert.ok(SCRIPT_SOURCES.includes("'self'"));
  });

  test("every script source reaches the header", () => {
    const policy = securityHeaders()["Content-Security-Policy"];

    for (const source of SCRIPT_SOURCES) {
      assert.ok(policy.includes(source), `script-src is missing ${source}`);
    }
  });

  test("the file says it is generated", () => {
    assert.match(headersFile(), /^# Generated by/);
  });
});

// A route-varying policy would break under soft navigation and only there, so
// nothing catches it by hand. harden() preserves a route-set CSP rather than
// clobbering it, which makes the mistake easy to make.
describe("the CSP is route-invariant", () => {
  test("securityHeaders() takes no required argument", () => {
    assert.equal(
      securityHeaders.length,
      0,
      "securityHeaders() gained a required parameter — if that is a route, soft navigation is now broken",
    );
  });

  test("the policy does not vary between calls", () => {
    assert.equal(
      securityHeaders()["Content-Security-Policy"],
      securityHeaders({})["Content-Security-Policy"],
    );
  });
});
