/**
 * The site's security headers, served from two places: public/_headers for
 * prerendered pages, src/middleware.ts for everything else. Edit this file —
 * scripts/generate-headers.ts writes public/_headers out of it.
 *
 * Plain TypeScript, no Astro-isms: Vite, bare Node and astro.config.ts all
 * load it.
 */

export interface HeaderContext {
  /** In dev the cursor Worker is on its own port; in production `'self'` covers it. */
  dev?: boolean;
}

/** Both schemes: the socket, and the presence count beside it. */
const DEV_MULTIPLAYER = "ws://localhost:8788 http://localhost:8788";

export function securityHeaders({ dev = false }: HeaderContext = {}) {
  return {
    "X-Content-Type-Options": "nosniff",
    "X-Frame-Options": "DENY",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "Permissions-Policy": "camera=(), microphone=(), geolocation=(), payment=()",
    "Strict-Transport-Security": "max-age=63072000; includeSubDomains",
    "Content-Security-Policy": contentSecurityPolicy(dev),
  } satisfies Record<string, string>;
}

/**
 * Everything the policy says that is not about scripts or styles. Shared
 * verbatim with Astro's `<meta>` CSP — a browser enforces both, and their
 * intersection is what binds. See CLAUDE.md § Maintenance.
 */
function baseDirectives(dev = false): string[] {
  return [
    "default-src 'self'",
    "base-uri 'self'",
    "form-action 'self'",
    "object-src 'none'",
    "font-src 'self'",
    // The cursor socket. Same origin, but `'self'` covering ws/wss is a CSP3
    // clarification some browsers were late to, so spell out the scheme.
    `connect-src 'self' wss://rcn.sh${dev ? ` ${DEV_MULTIPLAYER}` : ""}`,
    // Spotify spreads art across several scdn.co subdomains, hence wildcards.
    "img-src 'self' data: https://*.scdn.co https://*.spotifycdn.com https://avatars.githubusercontent.com https://upload.rcn.sh",
    "upgrade-insecure-requests",
  ];
}

/**
 * Every script host, for both surfaces: this header and, via astro.config.ts,
 * Astro's `<meta>` policy. A host named in only one is blocked. Keep `'self'`
 * — Astro's `resources` replaces its default rather than extending it. See
 * CLAUDE.md § Maintenance.
 *
 * The insights entry is the Cloudflare Web Analytics beacon: the host, not the
 * file, because the injected URL carries a version and a CSP path must match
 * exactly.
 */
export const SCRIPT_SOURCES = [
  "'self'",
  "https://static.cloudflareinsights.com",
];

/**
 * Do not remove 'unsafe-inline'. This header is the permissive floor and
 * Astro's hash-locked <meta> is what binds; dropping it here leaves an
 * intersection that admits no inline script at all. See CLAUDE.md § Maintenance.
 */
function contentSecurityPolicy(dev: boolean): string {
  return [
    ...baseDirectives(dev),
    "frame-ancestors 'none'",
    `script-src ${SCRIPT_SOURCES.join(" ")} 'unsafe-inline'`,
    "style-src 'self' 'unsafe-inline'",
  ].join("; ");
}

/** The contents of public/_headers. Always the production set. */
export function headersFile(): string {
  const rules = Object.entries(securityHeaders())
    .map(([name, value]) => `  ${name}: ${value}`)
    .join("\n");

  return `# Generated by scripts/generate-headers.ts — edit shared/security.ts.
#
# Statically served responses only; src/middleware.ts covers the rest. The
# Cloudflare adapter appends its own /_astro/* rule here at build time.

/*
${rules}
  Cache-Control: public, max-age=0, s-maxage=600, stale-while-revalidate=86400
`;
}
