/**
 * The site's security headers, written once and served from two places.
 *
 * Cloudflare answers a request for a prerendered page out of the asset store
 * without ever waking the Worker, so those responses are dressed by
 * public/_headers; anything the Worker renders — /guestbook, /api/*, server
 * islands — is dressed by src/middleware.ts. The two lists have to be the same
 * list, and keeping them as two hand-maintained copies meant every change to
 * one was a chance to forget the other. The comment saying so was the only
 * thing holding them together.
 *
 * So the set lives here, and scripts/generate-headers.ts writes public/_headers
 * out of it ahead of every dev run and build. Editing that file by hand does
 * nothing; edit this one.
 *
 * Deliberately plain TypeScript — no `@/` alias, no `import.meta.env`, nothing
 * Astro-shaped. Vite loads it for the middleware, bare Node loads it for the
 * generator, and astro.config.ts loads it for the CSP, and not all three
 * understand the same things.
 */

export interface HeaderContext {
  /**
   * Under `npm run dev:multiplayer` the cursor Worker runs on its own port,
   * which is a different origin and needs saying. In production it answers on
   * a route under rcn.sh and `'self'` covers it.
   */
  dev?: boolean;
}

/** Both schemes: the socket, and the presence count beside it. */
const DEV_MULTIPLAYER = "ws://localhost:8788 http://localhost:8788";

export function securityHeaders({ dev = false }: HeaderContext = {}) {
  return {
    "X-Content-Type-Options": "nosniff",
    "X-Frame-Options": "DENY",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "Permissions-Policy": "camera=(), microphone=(), geolocation=(), payment=()",
    "Strict-Transport-Security": "max-age=63072000; includeSubDomains",
    "Content-Security-Policy": contentSecurityPolicy(dev),
  } satisfies Record<string, string>;
}

/**
 * Everything the policy says that is not about scripts or styles.
 *
 * Shared verbatim between the header below and the `<meta>` element Astro
 * emits (see `security.csp` in astro.config.ts), because a browser enforces
 * every policy it is given and a directive present in one but absent from the
 * other is a directive with two different answers depending on which response
 * you happened to get.
 */
export function baseDirectives(dev = false): string[] {
  return [
    "default-src 'self'",
    "base-uri 'self'",
    "form-action 'self'",
    "object-src 'none'",
    "font-src 'self'",
    /*
      The multiplayer cursor socket. Same origin — it is a Worker route under
      rcn.sh, not a second hostname — but `'self'` covering ws/wss is a CSP3
      clarification some browsers were late to, so the scheme is spelled out.
    */
    `connect-src 'self' wss://rcn.sh${dev ? ` ${DEV_MULTIPLAYER}` : ""}`,
    // Spotify spreads art across several scdn.co subdomains (i, mosaic,
    // image-cdn-*), so the wildcard rather than the one host that shows up
    // most. Still scoped to Spotify.
    "img-src 'self' data: https://*.scdn.co https://*.spotifycdn.com https://avatars.githubusercontent.com https://upload.rcn.sh",
    "upgrade-insecure-requests",
  ];
}

/**
 * The header policy.
 *
 * `script-src` and `style-src` keep `'unsafe-inline'` here, which reads like
 * the opposite of the hardening it is part of. The reason is how two policies
 * compose: a browser given both a header and a `<meta>` CSP enforces *both*,
 * and a resource has to satisfy each one independently. So the strictness
 * lives in the meta element — Astro hashes every inline script and style it
 * emits and names those hashes there — and this header stays permissive on
 * exactly those two directives so that it cannot be the thing that blocks a
 * script the hashes have already vouched for.
 *
 * The net effect on an HTML response is the intersection of the two: Astro's
 * own hashed inline scripts run, and nothing else inline does. Tightening this
 * line instead would not improve on that; it would break every page, because
 * the header has no hashes to offer and `'self'` does not cover inline.
 *
 * What this header is still the only source of: `frame-ancestors`, which is
 * ignored inside a meta element, and the whole policy for responses that are
 * not HTML documents and so carry no meta at all.
 */
function contentSecurityPolicy(dev: boolean): string {
  return [
    ...baseDirectives(dev),
    "frame-ancestors 'none'",
    "script-src 'self' 'unsafe-inline'",
    "style-src 'self' 'unsafe-inline'",
  ].join("; ");
}

/**
 * The contents of public/_headers.
 *
 * Always the production set: this file only ever dresses responses Cloudflare
 * serves from the asset store, which is a thing that happens after a build.
 */
export function headersFile(): string {
  const rules = Object.entries(securityHeaders())
    .map(([name, value]) => `  ${name}: ${value}`)
    .join("\n");

  return `# Generated by scripts/generate-headers.ts — edit shared/security.ts.
#
# Security headers for statically served responses. Routes rendered by the
# Worker (/guestbook, /api/*, server islands) never touch this file —
# Cloudflare serves assets without invoking the Worker, and this only applies
# to those. src/middleware.ts carries the same set, from the same source, for
# everything else.
#
# The Cloudflare adapter appends its own immutable Cache-Control rule for
# /_astro/* to this file at build time.

/*
${rules}
`;
}
