import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { headersFile, securityHeaders } from "./security.ts";

/*
  The two surfaces this site is served from — the asset store, via
  public/_headers, and the Worker, via src/middleware.ts — used to carry two
  hand-written copies of this list with a comment asking whoever changed one to
  remember the other. This is that comment, in a form that fails.
*/
describe("security headers", () => {
  test("the generated file carries every header the Worker sets", () => {
    const file = headersFile();

    for (const [name, value] of Object.entries(securityHeaders())) {
      assert.ok(
        file.includes(`  ${name}: ${value}`),
        `public/_headers is missing ${name}`,
      );
    }
  });

  test("the file is shaped the way Cloudflare parses it", () => {
    const lines = headersFile().split("\n");
    const rule = lines.indexOf("/*");

    assert.ok(rule !== -1, "no path pattern");
    // Everything after the pattern is an indented header, or the trailing gap.
    for (const line of lines.slice(rule + 1)) {
      if (line === "") continue;
      assert.match(line, /^ {2}[\w-]+: .+$/, `not a header line: ${line}`);
    }
  });

  test("localhost is a development-only exception", () => {
    assert.ok(!securityHeaders()["Content-Security-Policy"].includes("localhost"));
    assert.ok(
      securityHeaders({ dev: true })["Content-Security-Policy"].includes(
        "ws://localhost:8788",
      ),
    );
  });

  /*
    The socket and the presence count are the same Worker on the same port, and
    a CSP that admits one but not the other is a feature that half works.
  */
  test("development admits both halves of the cursor Worker", () => {
    const policy = securityHeaders({ dev: true })["Content-Security-Policy"];

    assert.ok(policy.includes("ws://localhost:8788"));
    assert.ok(policy.includes("http://localhost:8788"));
  });

  /*
    Nothing in this repo loads the beacon — Cloudflare injects it at the edge —
    so the only place a path-scoped or missing allowance shows up is the
    deployed page's console, which is where it showed up last time.
  */
  test("the Web Analytics beacon is admitted by host", () => {
    assert.match(
      securityHeaders()["Content-Security-Policy"],
      /script-src[^;]* https:\/\/static\.cloudflareinsights\.com(?=[ ;]|$)/,
    );
  });

  test("the file says it is generated", () => {
    assert.match(headersFile(), /^# Generated by/);
  });
});

/*
  Soft navigation is only safe because the policy is one string for the whole
  site. A <ClientRouter /> swap does not reparse a header — the entry
  document's policy keeps governing every page reached after it — so a
  route-varying policy would break the second page onward, and do it
  invisibly, because a direct load of that same page works fine.

  Nothing structurally prevents someone adding a route argument here, and
  middleware's harden() deliberately preserves a route-set CSP rather than
  clobbering it, which makes the mistake easy to make and hard to see. This
  fails instead.
*/
describe("the CSP is route-invariant", () => {
  test("securityHeaders() takes no required argument", () => {
    assert.equal(
      securityHeaders.length,
      0,
      "securityHeaders() gained a required parameter — if that is a route, soft navigation is now broken",
    );
  });

  test("the policy does not vary between calls", () => {
    assert.equal(
      securityHeaders()["Content-Security-Policy"],
      securityHeaders({})["Content-Security-Policy"],
    );
  });
});
