import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as icons from "simple-icons";

/**
 * Pulls the brand marks /uses needs out of simple-icons into
 * src/lib/brand-marks.ts. Committed output, like world.ts, so only the handful
 * referenced ships. Marks with no entry are hand-drawn in UsesArt.astro.
 */

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "src/lib/brand-marks.ts");

/** Slug in simple-icons, keyed by the `art` name used in site.json. */
const WANTED: Record<string, string> = {
  typescript: "typescript",
  python: "python",
  astro: "astro",
  nextjs: "nextdotjs",
  react: "react",
  tailwind: "tailwindcss",
  cloudflare: "cloudflare",
  vercel: "vercel",
  postgres: "postgresql",
  linux: "linux",
  claude: "claude",
};

type Icon = { title: string; slug: string; path: string };

const bySlug = new Map<string, Icon>(
  Object.values(icons as Record<string, unknown>)
    .filter((value): value is Icon =>
      Boolean(
        value &&
          typeof value === "object" &&
          "slug" in value &&
          "path" in value &&
          "title" in value,
      ),
    )
    .map((icon) => [icon.slug, icon]),
);

async function main() {
  const entries: string[] = [];
  const missing: string[] = [];

  for (const [name, slug] of Object.entries(WANTED)) {
    const icon = bySlug.get(slug);
    if (!icon) {
      missing.push(`${name} (${slug})`);
      continue;
    }

    entries.push(
      `  ${name}: { title: ${JSON.stringify(icon.title)}, path: ${JSON.stringify(icon.path)} },`,
    );
  }

  if (missing.length > 0) {
    // Loud, not fatal: the page still builds, those items just lose their mark.
    console.warn(`[marks] no simple-icons entry for: ${missing.join(", ")}`);
  }

  const source = `// Generated by scripts/generate-brand-marks.ts — do not edit by hand.
// Regenerate with \`npm run marks\` after changing the list in that script.
//
// Paths are simple-icons, on a 24x24 viewBox. The marks remain their owners'
// trademarks and appear here only to identify the tools in use.

export type BrandMark = {
  /** The owner's own name for the mark, used as the accessible label. */
  title: string;
  /** Filled path data on a 24x24 grid. */
  path: string;
};

export const BRAND_MARKS: Record<string, BrandMark> = {
${entries.join("\n")}
};
`;

  await writeFile(OUT, source);
  console.log(
    `[marks] ${entries.length} marks written to src/lib/brand-marks.ts`,
  );
}

await main();
