import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { roomKey } from "../workers/multiplayer/src/protocol.ts";

/**
 * Writes shared/rooms.generated.ts: every path on this site that a cursor room
 * may exist for.
 *
 * Each distinct room key is a Durable Object that comes into existence by
 * being asked for. roomKey() checks that a key is *shaped* like a path here,
 * but shape is not identity — `/aaa`, `/aab` and so on all pass it, so a
 * script pointed at the socket could conjure as many rooms as it had patience
 * for. The Origin check in front is only enforced by browsers; anything that
 * is not one sets whatever header it likes.
 *
 * A list of the pages that actually exist is the thing that closes that, and
 * the site already knows what its pages are. Generated rather than committed
 * so it cannot drift from the content it describes — a post added without the
 * list being rebuilt would be a page whose readers are told cursors are not
 * available here, which is at least the honest failure.
 *
 * Reads the same two sources the site does, the same way scripts/generate-og.ts
 * does: bare Node cannot load Astro's content collection or the `@/` alias.
 */

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const POSTS_DIR = path.join(ROOT, "src/content/blog");
const SITE_JSON = path.join(ROOT, "src/content/site.json");
const OUT = path.join(ROOT, "shared/rooms.generated.ts");

/**
 * Every .md under src/content/blog, as collection ids.
 *
 * Drafts included, unlike the share cards. A draft is a real page under
 * `astro dev` — that is what drafts are for — and a reader looking at one
 * should not be told cursors are unavailable there. In production the page is
 * not built, so the extra key is simply a room nobody can reach, and the point
 * of the list is that it is bounded rather than that it is minimal.
 */
async function findPosts(dir: string, prefix = ""): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true }).catch(() => []);
  const ids: string[] = [];

  for (const entry of entries) {
    const id = prefix ? `${prefix}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      ids.push(...(await findPosts(path.join(dir, entry.name), id)));
    } else if (entry.name.endsWith(".md")) {
      ids.push(id.slice(0, -".md".length));
    }
  }

  return ids;
}

async function main() {
  const site = JSON.parse(await readFile(SITE_JSON, "utf8")) as {
    nav: { href: string }[];
  };

  const paths = [
    // Every page the nav lists, which is every page the site has.
    ...site.nav.map((entry) => entry.href),
    ...(await findPosts(POSTS_DIR)).map((id) => `/blog/${id}`),
  ];

  /*
    Normalised through the very function that will look them up, so the list
    cannot disagree with the lookup about what `/Blog/X/` is. Anything roomKey
    refuses would be unreachable in the list anyway, and is worth a word — it
    means a real page nobody can have cursors on.
  */
  const rooms = new Set<string>();
  for (const raw of paths) {
    const key = roomKey(raw);
    if (key === null) {
      console.warn(`[rooms] ${raw} is not a usable room key — skipped`);
      continue;
    }
    rooms.add(key);
  }

  const list = [...rooms].sort();
  const body = list.map((room) => `  ${JSON.stringify(room)},`).join("\n");

  await writeFile(
    OUT,
    `// Generated by scripts/generate-rooms.ts — do not edit.
//
// Every path a cursor room may exist for. See the script for why the list is
// the thing standing between a stranger and an unbounded number of Durable
// Objects.

export const ROOMS: readonly string[] = [
${body}
];
`,
  );

  console.log(`[rooms] wrote ${list.length} rooms`);
}

await main();
