import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { roomKey } from "../workers/multiplayer/src/protocol.ts";

/**
 * Writes shared/rooms.generated.ts: every path a cursor room may exist for.
 *
 * Each distinct room key spawns a Durable Object on request, and roomKey()
 * only checks the shape — `/aaa`, `/aab` and every other spelling pass it. A
 * list of the pages that actually exist is what bounds that. Generated so it
 * cannot drift from the content it describes.
 */

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const POSTS_DIR = path.join(ROOT, "src/content/blog");
const SITE_JSON = path.join(ROOT, "src/content/site.json");
const OUT = path.join(ROOT, "shared/rooms.generated.ts");

/**
 * Every .md under src/content/blog, as collection ids. Drafts included: they
 * are real pages under `astro dev`, and in production the extra key is just a
 * room nobody can reach. The list needs to be bounded, not minimal.
 */
async function findPosts(dir: string, prefix = ""): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true }).catch(() => []);
  const ids: string[] = [];

  for (const entry of entries) {
    const id = prefix ? `${prefix}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      ids.push(...(await findPosts(path.join(dir, entry.name), id)));
    } else if (entry.name.endsWith(".md")) {
      ids.push(id.slice(0, -".md".length));
    }
  }

  return ids;
}

async function main() {
  const site = JSON.parse(await readFile(SITE_JSON, "utf8")) as {
    nav: { href: string }[];
  };

  const paths = [
    // Every page the nav lists, which is every page the site has.
    ...site.nav.map((entry) => entry.href),
    ...(await findPosts(POSTS_DIR)).map((id) => `/blog/${id}`),
  ];

  // Normalised through the function that will look them up, so the two cannot
  // disagree about what `/Blog/X/` is.
  const rooms = new Set<string>();
  for (const raw of paths) {
    const key = roomKey(raw);
    if (key === null) {
      console.warn(`[rooms] ${raw} is not a usable room key — skipped`);
      continue;
    }
    rooms.add(key);
  }

  const list = [...rooms].sort();
  const body = list.map((room) => `  ${JSON.stringify(room)},`).join("\n");

  await writeFile(
    OUT,
    `// Generated by scripts/generate-rooms.ts — do not edit.
//
// Every path a cursor room may exist for; see the script for why it is bounded.

export const ROOMS: readonly string[] = [
${body}
];
`,
  );

  console.log(`[rooms] wrote ${list.length} rooms`);
}

await main();
